
-- Inserir novas perguntas para crianças de 18-24 meses (2 anos)

-- LINGUAGEM (18-24 meses)
INSERT INTO journey_bot_questions (
  question_text, 
  dimension, 
  age_min_months, 
  age_max_months, 
  order_index,
  feedback_yes,
  feedback_no,
  feedback_unknown,
  tips_yes,
  tips_no,
  tips_unknown,
  concern_level,
  active
) VALUES 
(
  'A criança fala pelo menos 50 palavras diferentes?',
  'language',
  18,
  24,
  10,
  'Fantástico! O vocabulário da criança está se desenvolvendo muito bem para a idade.',
  'Não se preocupe, alguns bebês desenvolvem a fala mais tarde. Vamos estimular a linguagem.',
  'Continue observando e contando as palavras que a criança fala. Anote-as para acompanhar o progresso.',
  ARRAY['Converse bastante durante atividades diárias', 'Leia livros e nomeie figuras', 'Celebre cada palavra nova que a criança fala'],
  ARRAY['Fale mais lentamente e repita palavras', 'Use gestos junto com as palavras', 'Cante músicas infantis simples'],
  ARRAY['Anote as palavras que a criança já fala', 'Observe se ela entende mais do que fala', 'Estimule com livros de figuras'],
  1,
  true
),
(
  'A criança combina duas palavras para formar frases simples (como "quero água" ou "papai foi")?',
  'language',
  18,
  24,
  11,
  'Excelente! A criança está começando a formar suas primeiras frases, um marco muito importante.',
  'Cada criança tem seu ritmo. Vamos trabalhar para estimular a combinação de palavras.',
  'Observe se a criança tenta se comunicar de outras formas e continue estimulando.',
  ARRAY['Repita as frases da criança expandindo-as', 'Use frases simples de duas palavras', 'Elogie sempre as tentativas de comunicação'],
  ARRAY['Modele frases simples durante o dia', 'Use livros com frases curtas', 'Repita palavras em contextos diferentes'],
  ARRAY['Observe por algumas semanas', 'Anote tentativas de combinação', 'Continue conversando normalmente'],
  1,
  true
),
(
  'A criança consegue seguir instruções simples de duas etapas (como "pega o brinquedo e me dá")?',
  'language',
  18,
  24,
  12,
  'Muito bom! A criança está entendendo e processando instruções mais complexas.',
  'Vamos trabalhar com instruções mais simples primeiro e depois aumentar a complexidade.',
  'Continue testando com diferentes tipos de instruções simples.',
  ARRAY['Dê instruções claras e aguarde a resposta', 'Use gestos para ajudar a compreensão', 'Celebre quando seguir instruções'],
  ARRAY['Comece com uma instrução por vez', 'Use palavras simples e conhecidas', 'Demonstre o que quer que faça'],
  ARRAY['Teste com instruções familiares', 'Observe se entende uma etapa por vez', 'Seja paciente e repita se necessário'],
  1,
  true
),
(
  'A criança consegue identificar e apontar para partes básicas do corpo quando solicitado?',
  'language',
  18,
  24,
  13,
  'Perfeito! A criança está desenvolvendo bem a compreensão das palavras e do próprio corpo.',
  'Vamos trabalhar mais com identificação de partes do corpo através de brincadeiras.',
  'Continue praticando e observe quais partes ela já conhece.',
  ARRAY['Brinque de "onde está o nariz?"', 'Use músicas sobre partes do corpo', 'Pratique durante o banho e troca'],
  ARRAY['Comece com partes mais óbvias como nariz e olhos', 'Aponte primeiro e depois peça para ela apontar', 'Use espelhos para mostrar partes do corpo'],
  ARRAY['Teste diferentes partes do corpo', 'Observe se ela toca quando você nomeia', 'Pratique em momentos de brincadeira'],
  0,
  true
),

-- MOTOR (18-24 meses)
(
  'A criança consegue correr sem cair frequentemente?',
  'motor',
  18,
  24,
  10,
  'Excelente! O equilíbrio e coordenação da criança estão se desenvolvendo muito bem.',
  'Não se preocupe, correr é uma habilidade que se desenvolve gradualmente. Vamos praticar.',
  'Continue observando o desenvolvimento da coordenação e equilíbrio.',
  ARRAY['Encoraje brincadeiras que envolvam correr', 'Crie espaços seguros para movimento', 'Brinque de pegar e fugir'],
  ARRAY['Comece com caminhada rápida', 'Pratique em superfícies macias e seguras', 'Segure as mãos durante tentativas de correr'],
  ARRAY['Observe se anda com firmeza', 'Teste em diferentes superfícies', 'Veja se tenta correr mesmo que caia'],
  1,
  true
),
(
  'A criança consegue subir e descer escadas com apoio?',
  'motor',
  18,
  24,
  11,
  'Muito bom! A criança está desenvolvendo força e coordenação nas pernas.',
  'Vamos trabalhar gradualmente essa habilidade sempre com segurança.',
  'Continue observando tentativas de subir e descer com apoio.',
  ARRAY['Pratique em escadas baixas e seguras', 'Segure sempre a mão da criança', 'Elogie cada degrau conquistado'],
  ARRAY['Comece com 1-2 degraus baixos', 'Use sempre apoio bilateral', 'Pratique subir antes de descer'],
  ARRAY['Observe se tenta subir móveis', 'Veja se demonstra interesse em escadas', 'Teste com apoio das duas mãos'],
  1,
  true
),
(
  'A criança consegue chutar uma bola enquanto caminha?',
  'motor',
  18,
  24,
  12,
  'Fantástico! A coordenação e equilíbrio da criança estão excelentes.',
  'Vamos praticar o movimento de chutar com atividades divertidas.',
  'Continue observando tentativas de chutar objetos durante brincadeiras.',
  ARRAY['Brinque de futebol no quintal', 'Use bolas de diferentes tamanhos', 'Celebre cada tentativa de chute'],
  ARRAY['Comece com bolas grandes e macias', 'Demonstre o movimento de chutar', 'Segure a mão da criança para dar apoio'],
  ARRAY['Observe se tenta chutar objetos no chão', 'Veja se demonstra interesse em bolas', 'Teste com diferentes objetos'],
  0,
  true
),
(
  'A criança consegue empilhar 4 ou mais blocos ou objetos similares?',
  'motor',
  18,
  24,
  13,
  'Excelente! A coordenação motora fina está se desenvolvendo muito bem.',
  'Vamos trabalhar gradualmente, começando com menos blocos.',
  'Continue observando tentativas de empilhar e construir.',
  ARRAY['Ofereça blocos de diferentes tamanhos', 'Brinque de construir torres juntos', 'Elogie tentativas mesmo que a torre caia'],
  ARRAY['Comece com 2 blocos grandes', 'Demonstre como empilhar', 'Use objetos que grudem ou encaixem'],
  ARRAY['Observe tentativas de empilhar', 'Veja se consegue pelo menos 2 blocos', 'Teste com objetos diferentes'],
  0,
  true
),

-- SOCIAL (18-24 meses)
(
  'A criança brinca próxima a outras crianças (brincadeira paralela)?',
  'social',
  18,
  24,
  10,
  'Muito bom! A criança está desenvolvendo habilidades sociais importantes.',
  'Vamos criar mais oportunidades para interação com outras crianças.',
  'Continue observando como a criança se comporta perto de outras crianças.',
  ARRAY['Organize encontros com outras crianças', 'Vá a parquinhos e praças', 'Observe sem interferir na brincadeira'],
  ARRAY['Comece com uma criança por vez', 'Fique próximo para dar segurança', 'Não force a interação'],
  ARRAY['Observe reações a outras crianças', 'Veja se demonstra interesse', 'Note se imita outras crianças'],
  1,
  true
),
(
  'A criança imita atividades domésticas como varrer, cozinhar ou cuidar de bonecas?',
  'social',
  18,
  24,
  11,
  'Fantástico! A criança está aprendendo através da imitação, que é fundamental.',
  'Vamos estimular mais brincadeiras de imitação no dia a dia.',
  'Continue observando tentativas de imitar atividades dos adultos.',
  ARRAY['Deixe a criança "ajudar" nas tarefas', 'Ofereça brinquedos que imitam objetos reais', 'Elogie tentativas de imitação'],
  ARRAY['Demonstre atividades simples para ela imitar', 'Use brinquedos de casinha', 'Seja paciente com as tentativas'],
  ARRAY['Observe se tenta imitar suas ações', 'Veja se brinca de "faz de conta"', 'Note interesse em atividades domésticas'],
  0,
  true
),
(
  'A criança demonstra empatia simples (como consolar quando alguém está triste)?',
  'social',
  18,
  24,
  12,
  'Maravilhoso! A criança está desenvolvendo empatia e compreensão emocional.',
  'Vamos trabalhar o reconhecimento de emoções através de exemplos.',
  'Continue observando reações da criança às emoções dos outros.',
  ARRAY['Nomeie emoções quando as vir', 'Leia livros sobre sentimentos', 'Elogie comportamentos empáticos'],
  ARRAY['Demonstre empatia na sua própria conduta', 'Use expressões faciais claras', 'Conforte a criança quando ela está triste'],
  ARRAY['Observe reações a choro ou tristeza', 'Veja se nota mudanças de humor nos outros', 'Teste reações a diferentes emoções'],
  1,
  true
),

-- SENSORIAL/COGNITIVO (18-24 meses)
(
  'A criança consegue resolver quebra-cabeças simples de 2-4 peças grandes?',
  'sensory',
  18,
  24,
  10,
  'Excelente! A capacidade de resolução de problemas está se desenvolvendo bem.',
  'Vamos começar com quebra-cabeças mais simples e ir aumentando a dificuldade.',
  'Continue observando tentativas de resolver problemas simples.',
  ARRAY['Ofereça quebra-cabeças apropriados para a idade', 'Ajude guiando as mãos da criança', 'Celebre quando conseguir encaixar peças'],
  ARRAY['Comece com formas geométricas simples', 'Use quebra-cabeças de madeira com pinos', 'Demonstre como encaixar as peças'],
  ARRAY['Observe se tenta encaixar peças', 'Veja se entende que peças têm lugares específicos', 'Teste persistência em atividades'],
  0,
  true
),
(
  'A criança demonstra entender causa e efeito (como apertar botão para fazer barulho)?',
  'sensory',
  18,
  24,
  11,
  'Muito bom! A criança está compreendendo como suas ações afetam o mundo.',
  'Vamos oferecer mais brinquedos e atividades que demonstram causa e efeito.',
  'Continue observando tentativas de descobrir como as coisas funcionam.',
  ARRAY['Ofereça brinquedos com botões e sons', 'Brinque com interruptores de luz (com supervisão)', 'Use brinquedos de causa e efeito'],
  ARRAY['Demonstre brinquedos antes de dar para a criança', 'Use brinquedos simples com uma ação', 'Repita demonstrações várias vezes'],
  ARRAY['Observe se repete ações que causam resultados', 'Veja se procura por consequências', 'Note se experimenta com objetos'],
  0,
  true
),
(
  'A criança consegue classificar objetos por forma básica (círculo, quadrado)?',
  'sensory',
  18,
  24,
  12,
  'Fantástico! A capacidade de classificação está se desenvolvendo muito bem.',
  'Vamos trabalhar com diferentes formas e classificações simples.',
  'Continue observando tentativas de organizar ou agrupar objetos.',
  ARRAY['Use brinquedos de encaixe de formas', 'Brinque de separar objetos por cor/forma', 'Elogie tentativas de classificação'],
  ARRAY['Comece com duas formas muito diferentes', 'Use objetos grandes e coloridos', 'Demonstre a classificação primeiro'],
  ARRAY['Observe se agrupa objetos similares', 'Veja se nota diferenças entre formas', 'Teste com objetos do dia a dia'],
  0,
  true
),
(
  'A criança reage adequadamente a diferentes temperaturas (quente, frio)?',
  'sensory',
  18,
  24,
  13,
  'Perfeito! A percepção sensorial da criança está bem desenvolvida.',
  'Vamos trabalhar a segurança e reconhecimento de diferentes temperaturas.',
  'Continue observando reações a diferentes estímulos sensoriais.',
  ARRAY['Ensine palavras "quente" e "frio"', 'Use brincadeiras sensoriais seguras', 'Sempre teste temperaturas antes de oferecer'],
  ARRAY['Comece com diferenças suaves de temperatura', 'Use água morna e fria em brincadeiras', 'Sempre supervisione atividades térmicas'],
  ARRAY['Observe reações a alimentos/bebidas', 'Veja se retira a mão de objetos quentes', 'Note reações a mudanças de temperatura'],
  2,
  true
);
