
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './database-types';

const SUPABASE_URL = "https://yxgbegmgqxtcbknxskpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4Z2JlZ21ncXh0Y2Jrbnhza3B6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNTExNjAsImV4cCI6MjA2NjcyNzE2MH0.FougzBKT8P_WO5kqLKQGjri_a5cDqCQ_dREzQWfV6aM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
